/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Rixael (https://sketchfab.com/rixael)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/house-draft-1ad594755ea44127bedaa23654237eea
Title: House Draft
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { a } from '@react-spring/three'
export function Model(props) {

    const modelRef = useRef()


    const { nodes, materials } = useGLTF('/materials/model.glb')
    return (
        <a.group ref={modelRef} {...props} >

            <mesh
                geometry={nodes.curve9_wood_0.geometry}
                material={materials.wood}
            />
            <mesh
                geometry={nodes.curve9_lambert1_0.geometry}
                material={materials.lambert1}
            />
            <mesh
                geometry={nodes.curve9_green_0.geometry}
                material={materials.green}
            />
            <mesh
                geometry={nodes.curve9_red_0.geometry}
                material={materials.material}
            />
            <mesh
                geometry={nodes.curve9_light_wall_0.geometry}
                material={materials.light_wall}
            />
            <mesh
                geometry={nodes.curve9_wood_dark_0.geometry}
                material={materials.wood_dark}
            />
            <mesh
                geometry={nodes.curve9_red_light_0.geometry}
                material={materials.red_light}
            />
            <mesh
                geometry={nodes.curve9_wall_0.geometry}
                material={materials.wall}
            />
            <mesh
                geometry={nodes.curve9_gold_0.geometry}
                material={materials.gold}
            />

        </a.group>
    )
}

